on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            ${{ vars.REGISTRY_HOST }}/${{ github.event.repository.name }}
          tags: |
            type=sha,prefix={{branch}}-
          flavor: |
            latest=true
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY_HOST }}
          username: ${{ vars.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: deploy.sh ${{ github.event.repository.name }} ${{ fromJSON(steps.meta.outputs.json).tags[0] }}
