on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: |
            ${{ vars.REGISTRY_HOST }}/${{ github.repository }}
          tags: |
            type=sha,prefix={{branch}}-
          flavor: |
            latest=true
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY_HOST }}
          username: ${{ vars.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
      - uses: kielabokkie/ssh-key-and-known-hosts-action@v1
        with:
          ssh-host: ${{ vars.SSH_HOST }}
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - env:
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
        run: |
          ssh -t ${{ vars.SSH_USERNAME }}@${{ vars.SSH_HOST }}
          sed -i 's|image:.*$|image: "${{ vars.REGISTRY_HOST }}/${{ github.repository }}:${{ fromJSON(steps.meta.outputs.json).tags[0] }}"|g' {{ vars.SSH_PATH }}
          docker login -u ${{ vars.REGISTRY_USERNAME }} -p "$REGISTRY_PASSWORD" ${{ vars.REGISTRY_HOST }} 
          docker compose up -d ${{ github.event.repository.name }}
